trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: $(image-name)

steps:

- script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
  displayName: Run QEMU

- task: Docker@2
  displayName: Build + Push (arm)
  inputs:
    containerRegistry: $(docker-hub)
    repository: $(docker-user)/$(imageName)
    command: buildAndPush
    tags: latest
- task: Docker@2
  displayName: Build + Push (x86)
  inputs:
    containerRegistry: $(docker-hub)
    repository: $(docker-user)/$(imageName)
    command: buildAndPush
    tags: latest
    Dockerfile: '**/x86.Dockerfile'